defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    docker:
    - image: circleci/node:8.12-browsers

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}

    - run: npm ci   
    
    - run: npm run build-storybook

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - persist_to_workspace:
        root: /home/circleci
        paths:
          - repo

  deploy:
    docker:
    - image: microsoft/azure-cli

    steps:
    
    - attach_workspace:
        at: repo
    
    
    

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        
